### PR TITLE
Fix for multiple tab container scenario

### PR DESCRIPTION
**Pull request by austinmcnicholas**
may not want to accept this fork request because i also added an option to trigger a microflow on the click of the tab, but ill outline the issue that i fixed.

If the page with your tab container is currently opened and you click on the navigation bar to open the same page the widget wouldn't work. What was happening was at the time of the widget creation, two tab containers would exist, one that is being destroyed and one that is being created. To handle this, I used the below code.

                               //handle the case that the page is being opened again
				var list = dojo.query("."+this.tabclass); //returns a list of tabs from the dom
				if (list){
					list.forEach(function (item){
						var node = dijit.byNode(item); // register each item
						//if multiple items are returned then that means one container is in the process of being destroyed and the other is being created.
						//check for the being destroyed flag and set the tab container correctly
						if (node && !node._beingDestroyed){ 
							this._tabContainer = node;
						}
					}.bind(this));
				}

### CODE REVIEW

**Comment by ivosturm** [comment]
Hi Austin,

Thanks for sharing the fix. I will check it later this week and if applicable deploy the new version to the AppStore.

**Comment by ivosturm** [comment]
Hi Austin,

I tried reproducing this, but for me this works in a test project. Does your page have a lot of objects (dataviews/grids), hence timing of the loading could be a player here? Do you have the TabSwitcher widget on the bottom of the DataView?

**Comment by austinmcnicholas** [comment]
Hi Ivo,

I had the widget at the bottom of the dataview, and the page just had a
dataview with a tab container in it.

Here is a test project that demonstrates it. When i first load the page and
i click between the tabs, the tab attribute is updated. If i click the home
navigation button and do the same test, nothing happens.

https://drive.google.com/file/d/1OUCheLRnwj2GTAYEj2DNsLdiGn3QdhiL/view?usp=sharing

**Comment by ivosturm** [comment]
Hi Austin, today I added a new version of the widget to the AppStore including the bugfix you mentioned here. SInce I am not adding the on click microflow I am not merging the pull request. Thanks for the help, I mentioned your help in the release notes!

**Pull request closed without merging**
